---
- hosts: slurm-masters
  become: yes
  roles:
    - { role: nfs, nfs_is_server: yes }
    - { role: nfs, nfs_is_client: yes }     # make sure you don't export/mount to the same place

- hosts: compute-nodes
  become: yes
  roles:
    - { role: nfs, nfs_is_client: yes }
